# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Jandex CI

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java-version: [8, 11]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java.name }}
      # Uses sha for added security since tags can be updated
      uses: joschi/setup-jdk@ccd4eb6437f6a33d3c033551a6004cc6f3078307
      with:
        java-version:  ${{ matrix.java-version }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
